"""
Offline generator that produces a DATED signal schedule over the model's
real, held-out TEST PERIOD: 2017-01-01 00:00 to 2017-06-30 23:00 (ADR-008's
temporal split - train is every row strictly before this window, test is
every row from it onward). This is NOT a forecast into the future: every
feature value for every hour comes from a real row already present in
data/traffic_final_cleaned.csv, because the target window sits inside the
dataset, not past its end (see DECISIONS.md's dated-schedule ADR for why
an annual, forward-looking window was rejected - the dataset ends
2017-06-30 and a forward window would need data that does not exist).

models/count_model.joblib is loaded as-is and used only for .predict() -
this script never calls .fit() and never retrains anything.

traffic_sim.py never runs this logic at run time - it only reads the
finished CSV (SECTION 15's approval gate). Running this script only ever
writes a data file; it has no effect on the live simulation, and the
"signals never react to incidents" rule (ADR-005) is untouched.

This file is independent of generate_timeline.py's weekly, hour-of-week
template (signal_schedule_plan.csv, which stays on disk untouched and
unregenerated by this script) - it reuses generate_timeline.py's
allocate_green() unchanged (same ADR-021 cycle/floor/rounding), but builds
its own dated rows rather than an hour-of-week template.

Usage:
    python generate_dated_schedule.py
"""

import csv

import joblib
import pandas as pd

from data_prep import DATA_PATH, FEATURE_COLUMNS, load_and_engineer, feature_matrix
from generate_timeline import ROTATION, CYCLE_SECONDS, MODEL_PATH, allocate_green
import model_wrapper  # noqa: F401 - required so joblib.load() can unpickle DiffTargetRandomForest

# The model's real, held-out test period (ADR-008) - not chosen freely.
# See model_card.json's split_date: train is every row before this, test
# is every row from it onward, so this window was never seen in training.
WINDOW_START = pd.Timestamp("2017-01-01 00:00")
WINDOW_END = pd.Timestamp("2017-06-30 23:00")

OUTPUT_PATH = "signal_schedule_dated.csv"


def build_dated_schedule(start=WINDOW_START, end=WINDOW_END):
    """
    Returns a list of row dicts: datetime, hour_of_week, road,
    predicted_count, green_seconds - one row per (hour, road) in
    [start, end] inclusive.

    Raises ValueError, rather than silently proceeding, if any row in the
    window is flagged Synthetic_Segment_Unverified (the window must be
    entirely real data - see STEP 0's check c) or if any hour in the
    window is missing after feature engineering (a dropped-for-NaN row
    would mean a feature could not be computed from real prior data alone
    - see STEP 0's check e).
    """
    features, _rows_dropped_for_nan = load_and_engineer(DATA_PATH)
    window = features[
        (features["DateTime"] >= start) & (features["DateTime"] <= end)
    ].copy()

    if window["Synthetic_Segment_Unverified"].any():
        bad = window[window["Synthetic_Segment_Unverified"]]
        raise ValueError(
            f"{len(bad)} row(s) in [{start}, {end}] are "
            "Synthetic_Segment_Unverified=True - refusing to build a dated "
            "schedule from fabricated data. Offending rows:\n"
            f"{bad[['DateTime', 'Road']].to_string(index=False)}"
        )

    expected_hours = pd.date_range(start, end, freq="h")
    for road in ROTATION:
        present = set(window.loc[window["Road"] == road, "DateTime"])
        missing = sorted(set(expected_hours) - present)
        if missing:
            raise ValueError(
                f"Road '{road}' is missing {len(missing)} hour(s) in the window "
                f"after feature engineering (dropped for insufficient lag "
                f"history, or absent from the source data): "
                f"{missing[:5]}{'...' if len(missing) > 5 else ''}"
            )

    model = joblib.load(MODEL_PATH)

    rows = []
    for dt in expected_hours:
        hour_rows = window[window["DateTime"] == dt].set_index("Road")
        hour_rows = hour_rows.loc[ROTATION]  # fixed, deterministic order

        X, _ = feature_matrix(hour_rows)
        assert list(X.columns) == FEATURE_COLUMNS

        predicted_counts = dict(zip(ROTATION, model.predict(X)))
        green_seconds, _n_clamped = allocate_green(predicted_counts, CYCLE_SECONDS)

        hour_of_week = dt.dayofweek * 24 + dt.hour  # Monday 00:00 = 0 .. Sunday 23:00 = 167
        for road in ROTATION:
            rows.append({
                "datetime": dt.isoformat(),
                "hour_of_week": hour_of_week,
                "road": road,
                "predicted_count": predicted_counts[road],
                "green_seconds": green_seconds[road],
            })

    return rows


def write_dated_schedule_csv(rows, output_path=OUTPUT_PATH):
    fields = ["datetime", "hour_of_week", "road", "predicted_count", "green_seconds"]
    with open(output_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    print(f"Building dated schedule for {WINDOW_START} to {WINDOW_END} "
          f"(the model's real, held-out test period - ADR-008).")
    rows = build_dated_schedule()
    print(f"Built {len(rows)} rows ({len(rows) // len(ROTATION)} hours x "
          f"{len(ROTATION)} roads).")
    write_dated_schedule_csv(rows)
    print(f"Wrote {OUTPUT_PATH}")
